// <auto-generated />
using System;
using Lore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lore.Data.Migrations
{
    [DbContext(typeof(LoreDbContext))]
    [Migration("20260812232411_MakeDirectoryPathUnique")]
    partial class MakeDirectoryPathUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Lore.Data.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("keywords");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_document_types");

                    b.ToTable("document_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "invoice, bill, amount due, payment due date, invoice number, line items, billing address, remit payment to, total balance, vendor invoice, tax rate",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Invoice"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "receipt, proof of payment, transaction confirmation, payment received, sales receipt, cash register, total paid, payment method, change due, subtotal",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Receipt"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "financial statement, account statement, monthly summary, credit card statement, bank statement, beginning balance, ending balance, ledger statement",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Statement"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "contract, agreement, non-disclosure agreement, terms and conditions, legally binding, signatures, execution date, effective date, obligation, breach, clauses, parties hereto",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Contract"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "application form, registration form, questionnaire, fillable fields, survey, intake form, official application, checkboxes, applicant signature",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Form"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "certificate of completion, diploma, official certification, accredited, awarded to, certification of compliance, achievement, credential, birth certificate",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Certificate"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "driver license, passport, national ID card, government identification, date of birth, identity verification, photo ID, SSN, social security card",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Identification"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "letter, email message, internal memo, memorandum, subject line, dear sir or madam, warm regards, notification letter, formal notice",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Correspondence"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "audit report, business report, analytical report, whitepaper, executive summary, findings, assessment, study results, quarterly report, research analysis",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Report"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "user manual, technical guide, API reference, instruction manual, operation manual, developer documentation, installation guide, troubleshooting",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "slide deck, powerpoint presentation, keynote, pitch deck, slide summary, presentation agenda, overview presentation",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Presentation"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "spreadsheet data, tabular format, financial model, excel data, csv export, columns and rows, calculated totals, tabular analysis",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spreadsheet"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "resume, curriculum vitae, work experience, employment history, technical skills, education background, professional summary, references",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Resume"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "academic research paper, abstract, methodology, literature review, bibliography, citations, peer-reviewed, doi, journal article",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ResearchPaper"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "handwritten notes, meeting notes, personal memo, quick thoughts, scratchpad, bulleted agenda, informal summary",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Note"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "tax return, Form W-2, Form 1099, IRS tax filing, tax deduction, gross income, tax year, withholding, revenue service",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TaxDocument"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "insurance policy, claim form, explanation of benefits, coverage details, policy number, deductible, insured party, premium, claim number",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "InsuranceDocument"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "medical chart, clinical report, prescription, physician notes, diagnostic results, patient history, medical examination, lab report",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MedicalRecord"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "bank account statement, checking account, savings statement, deposits, withdrawals, routing number, daily balance summary",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BankStatement"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "short story, poem, poetry stanza, novel excerpt, fictional writing, prose, essay, song lyric, creative manuscript",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CreativeWriting"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "uncategorized format, standard text document, general file, unspecified document format",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Lore.Data.Models.FileEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("directory");

                    b.Property<int?>("DocumentTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_type_id");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("extension");

                    b.Property<DateTime>("FileCreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_created_at");

                    b.Property<DateTime>("FileModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_modified_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int?>("PrimaryCategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("primary_category_id");

                    b.Property<string>("ProcessStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("process_status");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("ix_files_document_type_id");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ix_files_path");

                    b.HasIndex("PrimaryCategoryId")
                        .HasDatabaseName("ix_files_primary_category_id");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Lore.Data.Models.FileEntryChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("chunk_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("FileEntryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_entry_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_file_chunks");

                    b.HasIndex("FileEntryId")
                        .HasDatabaseName("ix_file_chunks_file_entry_id");

                    b.ToTable("file_chunks", (string)null);
                });

            modelBuilder.Entity("Lore.Data.Models.FileSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExcludePattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("exclude_pattern");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.HasKey("Id")
                        .HasName("pk_file_sources");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ix_file_sources_path");

                    b.ToTable("file_sources", (string)null);
                });

            modelBuilder.Entity("Lore.Data.Models.PrimaryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("keywords");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_primary_categories");

                    b.ToTable("primary_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "accounting, banking, payments, billing, invoices, receipts, taxation, payroll, financial statements, balance sheet, general ledger, income, expenses, monetary transactions, wire transfer, credit card statement",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Financial"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "legal agreements, litigation, compliance, intellectual property, contracts, court orders, power of attorney, statutes, regulations, non-disclosure, terms of service, liabilities, governance, legal counsel",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Legal"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "healthcare, medical treatment, clinical records, prescriptions, medical diagnosis, lab results, patient charts, physician notes, health insurance claims, pharmacy, clinical trials, pathology",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medical"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "government agencies, public records, official identification, immigration, passports, visas, permits, licenses, municipal records, regulatory filings, citizenship, civil documents, social security",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Government"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "software development, engineering, IT infrastructure, source code, API reference, system architecture, database schema, DevOps, hardware specifications, networking, technical manuals, algorithms",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Technical"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "general business operations, strategic planning, management, corporate policies, meeting minutes, company vision, human resources, organizational hierarchy, project management, business proposals",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Business"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "teaching, learning, courses, academic research, curricula, textbooks, training materials, lecture notes, certifications, diplomas, school assignments, student records, syllabus",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Educational"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "advertising, brand strategy, sales materials, promotional campaigns, press releases, market research, customer outreach, target demographics, social media plans, pitch decks, product launches",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "personal or professional communication, letters, email threads, internal memos, formal notices, inter-office messaging, newsletters, standard mail, written communications",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Correspondence"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "creative writing, literary work, poetry, stories, screenplays, song lyrics, personal essays, fiction, artwork descriptions, journal entries, manuscripts, creative prose",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Creative"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Keywords = "uncategorized content, miscellaneous files, general text, unidentified material, generic documents",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Lore.Data.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Lore.Data.Models.FileEntry", b =>
                {
                    b.HasOne("Lore.Data.Models.DocumentType", "DocumentType")
                        .WithMany("FileEntries")
                        .HasForeignKey("DocumentTypeId")
                        .HasConstraintName("fk_files_document_types_document_type_id");

                    b.HasOne("Lore.Data.Models.PrimaryCategory", "PrimaryCategory")
                        .WithMany("FileEntries")
                        .HasForeignKey("PrimaryCategoryId")
                        .HasConstraintName("fk_files_primary_categories_primary_category_id");

                    b.Navigation("DocumentType");

                    b.Navigation("PrimaryCategory");
                });

            modelBuilder.Entity("Lore.Data.Models.FileEntryChunk", b =>
                {
                    b.HasOne("Lore.Data.Models.FileEntry", "FileEntry")
                        .WithMany("Chunks")
                        .HasForeignKey("FileEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_chunks_files_file_entry_id");

                    b.Navigation("FileEntry");
                });

            modelBuilder.Entity("Lore.Data.Models.DocumentType", b =>
                {
                    b.Navigation("FileEntries");
                });

            modelBuilder.Entity("Lore.Data.Models.FileEntry", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Lore.Data.Models.PrimaryCategory", b =>
                {
                    b.Navigation("FileEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
